name: Build, test and publish
on:
  push:
    branches:    
      - main
    tags-ignore:        
      - build-number-**

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      use-msbuild: true
      install-latest-msbuild: true
      conventional-commits-publish-conditions: false
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
      personal-token: ${{ secrets.PERSONAL_TOKEN }}
